name: Gradle Build & Test

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Version de Java'
        required: false
        default: '17'
        type: string
      gradle-task:
        description: 'Gradle tasks to run'
        required: false
        default: 'build'
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Run Gradle tasks
        run: ./gradlew ${{ inputs.gradle-task }}
