name: Kotlin CI

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Version de Java'
        required: false
        default: '17'
        type: string
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  # Draft PR → toutes branches sauf main
  draft-pr:
    if: github.ref_name != 'main'
    uses: ./.github/workflows/auto-pr.yml
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}


  # Ne s'exécute que sur PR non-draft
  build-and-test:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    uses: ./.github/workflows/gradle-build.yml
    with:
      java-version: ${{ inputs.java-version }}
      gradle-task: ${{ inputs.gradle-task }}

