name: Kotlin CI

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Version de Java'
        required: false
        default: '17'
        type: string
      gradle-task:
        description: 'Gradle tasks to run'
        required: false
        default: 'build test'
        type: string
      is-draft:
        description: 'Indique si la PR est en draft'
        required: true
        type: boolean
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  # Draft PR → toutes branches sauf main
  draft-pr:
    if: github.ref_name != 'main'
    uses: ./.github/workflows/auto-pr.yml
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}


  # Build & Test Gradle (PR non-draft)
  build-and-test:
    if: ${{ inputs.is-draft == false }}
    uses: ./.github/workflows/gradle-build.yml
    with:
      java-version: ${{ inputs.java-version }}
      gradle-task: ${{ inputs.gradle-task }}

