name: Kotlin CI

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Version de Java'
        required: false
        default: '17'
        type: string

jobs:
  draft-pr:
    uses: ./.github/workflows/auto-pr.yml
